version: "2.0"
services:
  web:
    restart: always
    build:
      dockerfile: Dockerfile.web
      context: .
      args:
        - "password"
    expose:
      - "8000"
    volumes:
      - ./:/var/www/tab
    links:
      - "mysql:mysql"
    env_file:
      - .env
    command: /usr/local/bin/gunicorn mittab.wsgi:application -w 2 -b :8000 -t 300
    depends_on:
      - "mysql"

  discord:
    restart: always
    build:
      dockerfile: Dockerfile.discord
      context: .
    env_file:
      - .env
    command: pipenv run python start_discord.py $DISCORD_SERVER_NAME

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    env_file:
      - .env

  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/www/static
    volumes_from:
      - web
    links:
      - web:web
volumes:
  my-db:
