- teams_public:
  name: teams_public
  description: "Check this box to make the team list publicly visible"
  value: false
  type: boolean
- judges_public:
  name: judges_public
  description: "Check this box to make the judges list publicly visible"
  value: false
  type: boolean
- lenient_late:
  name: lenient_late
  description: "The latest round where people who do not show up are given average speaks instead of speaks of 0 by default. Note: This only applies before the round. If you change this after the round was paired, it will not take effect. You can manually allow a lenient_late in the admin interface."
  value: 0
- max_eballot_speak:
  name: max_eballot_speak
  description: "The maximum speaker score allowed to be submitted by an e-ballot Note: This value will be allowed. In other words, if the value is 35, a 35 does not have to be justified to tab staff but a 36 does"
  value: 35
- min_eballot_speak:
  name: min_eballot_speak
  description: "The minimum speaker score allowed to be submitted by an e-ballot Note: This value will be allowed. In other words, if the value is 15, a 15 does not have to be justified to tab staff but a 14 does"
  value: 15
- nov_teams_to_break:
  name: nov_teams_to_break
  description: "The number of novice teams to be included in the break (exclusive of novice teams who are varsity breaking)"
  value: 4
- var_teams_to_break:
  name: var_teams_to_break
  description: "The number of varsity teams to be included in the break."
  value: 8
- nov_panel_size:
  name: nov_panel_size
  description: "The number of judges on a novice outs panel"
  value: 3
- var_panel_size:
  name: var_panel_size
  description: "The number of judges on a varsity outs panel"
  value: 3
- var_to_nov:
  name: var_to_nov
  description: "The offset of the novice break to the varsity break.  If novice semis happen when varsity quarters happen, the offset should be 1.  If novice semis happen when varsity octofinals happen, the offset should be 2."
  value: 2
- gov_opp_display:
  name: gov_opp_display
  description: "A toggle to switch the outrounds view from displaying Gov and Opp (when value is 1) and Team 1 and Team 2 (when value is 2)"
  value: false
  type: boolean
- sidelock:
  name: sidelock
  description: "A toggle to indicate whether you are side-locking outrounds.  If 1, then the gov opps for outrounds will not be random, but will adhere to sidelocks, and will be indicated on the pairing card, and bolded on the front-facing pairing display."
  value: false
  type: boolean
- choice:
  name: choice
  description: "A toggle to indicate whether you would like to display who has choice, whether you would like this to be  be indicated on the pairing card, and bolded on the front-facing pairing display"
  value: false
  type: boolean
- disable_room_seeding:
  name: enable_room_seeding
  description: "Toggle to enable room seeding. When enabled, the best rooms go to the highest seeded rooms."
  value: true
  type: boolean
- official_apda_tournament:
  name: official_apda_tournament
  description: "A toggle to indicate whether this is an officially sanctioned APDA tournament. If true, the APDA IDs will be used for the tournament."
  value: false
  type: boolean
